### ISSUE TITLE
Linting CI is broken

### ISSUE THREAD

**Issue by loostrum** [dianna-ai/dianna#423]
See the following screenshot from https://github.com/dianna-ai/dianna/actions/runs/3593771040/jobs/6051161094:

![image](https://user-images.githubusercontent.com/6370787/205088266-35901e92-7ee6-4509-a9c6-401a4473ff2d.png)

**Comment by loostrum** [comment]
We already install prospector[with_pyroma] exactly as suggested in the screenshot and it worked before. Perhaps an update to prospector/pyroma broke this

**Comment by egpbos** [comment]
Highly likely. There was an update yesterday: https://pypi.org/project/prospector/#history Also an update three hours ago, so maybe it was fixed. But looking at the log of that run, I also see this:

<img width="564" alt="Schermafbeelding 2022-12-02 om 16 22 23" src="https://user-images.githubusercontent.com/6146598/205326501-30f67b26-439c-4c64-be61-91cf9e2e506c.png">

Not sure if 1.8.2 fixes that...

**Comment by egpbos** [comment]
Maybe just try installing pyroma explicitly? Or disable it in linting config, not sure what it does or whether it is even used here anyway (it gives a score, not a fail/pass, I think).

**Comment by loostrum** [comment]
Ah good catch. There's already an open issue in the prospector repo: https://github.com/PyCQA/prospector/issues/545
It can still fail even if pyroma is installed, so we could also just pin the prospector version to 1.8.0 for now

**Comment by loostrum** [comment]
I'm also not sure what pyroma actually does. I opened a PR with the least-effort way of getting it to run again: pinning the version
